force-app/main/driver-assistant/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <label>Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <displayFormat>R-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Route__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/driver-assistant/objects/Route_Assignment__c/Route_Assignment__c.object-meta.xml
<CustomObject>
    <label>Route Assignment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Route_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Route Assignments</relationshipLabel>
    <relationshipName>Route_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Route_Assignment__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Route Assignments</relationshipLabel>
    <relationshipName>Route_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Route_Event__c/Route_Event__c.object-meta.xml
<CustomObject>
    <label>Route Event</label>
    <nameField>
        <label>Route Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Route_Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <scale>5</scale>
    <type>Location</type>
</CustomField>

force-app/main/driver-assistant/objects/Route_Event__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Route Events</relationshipLabel>
    <relationshipName>Route_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Route_Event__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stop</label>
    <referenceTo>Stop__c</referenceTo>
    <relationshipLabel>Route Events</relationshipLabel>
    <relationshipName>Route_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Route_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arrival</fullName>
            </value>
            <value>
                <fullName>Departure</fullName>
            </value>
            <value>
                <fullName>Load</fullName>
            </value>
            <value>
                <fullName>Unload</fullName>
            </value>
            <value>
                <fullName>Delay</fullName>
            </value>
            <value>
                <fullName>Incident</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/Stop__c.object-meta.xml
<CustomObject>
    <label>Stop</label>
    <nameField>
        <label>Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Stop__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <label>Sequence Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Origin</fullName>
            </value>
            <value>
                <fullName>Stop</fullName>
            </value>
            <value>
                <fullName>Destination</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/driver-assistant/classes/RouteMapController.cls
/**
 * Created by Vsevolod_Bogdanov on 2/7/2025.
 */

public without sharing class RouteMapController {
    public static String getRouteId() {
        String contactId = (String) [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1]?.ContactId ?? '';
        if (!String.isBlank(contactId)) {
            String result = (String) [
                    SELECT Route__c
                    FROM Route_Assignment__c
                    WHERE Contact__c = :contactId AND Route__r.Status__c = 'In-Progress'
                    LIMIT 1
            ]?.Route__c;

            return result;
        }

        return '';
    }

    @AuraEnabled(Cacheable=true)
    public static Map<String, Object> getRoutePoints(String routeId) {
        Map<String, Object> result = new Map<String, Object>();
        if (String.isBlank(routeId)) {
            routeId = getRouteId();
        }

        if (!String.isBlank(routeId)) {

            List<Stop__c> routePoints = [
                    SELECT Name, Sequence_Number__c, Type__c, Facility__r.Address__c
                    FROM Stop__c
                    WHERE Route__c = :routeId
                    ORDER BY Sequence_Number__c
            ];
            result.put('routePoints', routePoints);

            List<Route_Event__c> routeEvents = [
                    SELECT Name, Description__c, Location__c, Location__Latitude__s, Location__Longitude__s
                    FROM Route_Event__c
                    WHERE Route__c = :routeId
            ];

            result.put('routeEvents', routeEvents);
        }

        return result;
    }

}