force-app/main/driver-assistant/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <label>Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <displayFormat>R-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Route_Assignment__c/Route_Assignment__c.object-meta.xml
<CustomObject>
    <label>Route Assignment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Route_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Route Assignments</relationshipLabel>
    <relationshipName>Route_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Route_Assignment__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Route Assignments</relationshipLabel>
    <relationshipName>Route_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/Stop__c.object-meta.xml
<CustomObject>
    <label>Stop</label>
    <nameField>
        <label>Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Stop__c/fields/Expected_Arrival_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Expected_Arrival_End_Time__c</fullName>
    <label>Expected Arrival End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Expected_Arrival_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Expected_Arrival_Start_Time__c</fullName>
    <label>Expected Arrival Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Expected_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Expected_Departure_Time__c</fullName>
    <label>Expected Departure Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <label>Sequence Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <label>Trip</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Origin</fullName>
            </value>
            <value>
                <fullName>Stop</fullName>
            </value>
            <value>
                <fullName>Destination</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/driver-assistant/classes/RouteTableController.cls
public with sharing class RouteTableController {
    @AuraEnabled(cacheable=true)
    public static List<Route__c> getRoutes(Id contactId) {
        if (contactId == null) {
            return [
                SELECT Id, Name, 
                    (SELECT Name, Sequence_Number__c, Trip__c, 
                    Expected_Arrival_Start_Time__c, Expected_Arrival_End_Time__c, 
                    Expected_Departure_Time__c, Facility__r.Address__City__s,
                    Facility__r.Address__StateCode__s
                    FROM Stops__r 
                    ORDER BY Sequence_Number__c) 
                FROM Route__c
            ];
        }

        return [
            SELECT Id, Name, 
                (SELECT Name, Sequence_Number__c, Trip__c, 
                Expected_Arrival_Start_Time__c, Expected_Arrival_End_Time__c, 
                Expected_Departure_Time__c, Facility__r.Address__City__s,
                Facility__r.Address__StateCode__s
                FROM Stops__r 
                ORDER BY Sequence_Number__c) 
            FROM Route__c
            WHERE Id IN (SELECT Route__c FROM Route_Assignment__c WHERE Contact__c = :contactId)
        ];
    }
}