force-app/main/driver-assistant/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <label>Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <displayFormat>R-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Route__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/driver-assistant/objects/Route_Assignment__c/Route_Assignment__c.object-meta.xml
<CustomObject>
    <label>Route Assignment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Route_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Route Assignments</relationshipLabel>
    <relationshipName>Route_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Route_Assignment__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Route Assignments</relationshipLabel>
    <relationshipName>Route_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Route_Event__c/Route_Event__c.object-meta.xml
<CustomObject>
    <label>Route Event</label>
    <nameField>
        <label>Route Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Route_Event__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Route Events</relationshipLabel>
    <relationshipName>Route_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Route_Event__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stop</label>
    <referenceTo>Stop__c</referenceTo>
    <relationshipLabel>Route Events</relationshipLabel>
    <relationshipName>Route_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Route_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arrival</fullName>
            </value>
            <value>
                <fullName>Departure</fullName>
            </value>
            <value>
                <fullName>Load</fullName>
            </value>
            <value>
                <fullName>Unload</fullName>
            </value>
            <value>
                <fullName>Delay</fullName>
            </value>
            <value>
                <fullName>Incident</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/Stop__c.object-meta.xml
<CustomObject>
    <label>Stop</label>
    <nameField>
        <label>Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Stop__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <label>Sequence Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <label>Trip</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Origin</fullName>
            </value>
            <value>
                <fullName>Stop</fullName>
            </value>
            <value>
                <fullName>Destination</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Origin</fullName>
            </value>
            <value>
                <fullName>Stop</fullName>
            </value>
            <value>
                <fullName>Destination</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/driver-assistant/classes/RouteEventTriggerTest.cls
@IsTest
private class RouteEventTriggerTest {
    
    @testSetup static void testSetup() {
        Contact testContact = new Contact(FirstName = 'Test', LastName = 'Contact');
        insert testContact;
        
        Route__c route = new Route__c(Status__c = 'New');
        insert route;
        
        Route_Assignment__c routeAssignment = new Route_Assignment__c(Route__c = route.Id, Contact__c = testContact.Id);
        insert routeAssignment;
        
        Facility__c facility = new Facility__c(Name = 'Test Facility');
        insert facility;
        
        List<Stop__c> stops = new List<Stop__c>();
        
        Stop__c stopOrigin = new Stop__c();
        stopOrigin.Name = 'Test stop';        
        stopOrigin.Route__c = route.Id;
        stopOrigin.Facility__c = facility.Id;
        stopOrigin.Sequence_Number__c = 1;
        stopOrigin.Trip__c = 'Origin';
        stops.add(stopOrigin);
        
        Stop__c stopDestination = new Stop__c();
        stopDestination.Name = 'Test stop';        
        stopDestination.Route__c = route.Id;
        stopDestination.Facility__c = facility.Id;
        stopDestination.Sequence_Number__c = 1;
        stopDestination.Trip__c = 'Destination';
        stops.add(stopDestination);
        
        insert stops;        
	}
    
    @IsTest
    private static void insertRouteEventWithArrivalStatus() {
        Stop__c originStop = [SELECT Id, Route__c FROM Stop__c WHERE Trip__c = 'Origin' LIMIT 1];
        
        Route_Event__c routeEvent = new Route_Event__c(Route__c = originStop.Route__c, Stop__c = originStop.Id,
                                                       Type__c = 'Arrival');
        
        Test.startTest();
        insert routeEvent;
        Test.stopTest();
        
        Route__c route = [SELECT Status__c FROM Route__c LIMIT 1];
        
        Assert.areEqual('In-Progress', route.Status__c);
    }
    
    @IsTest
    private static void insertRouteEventWithDepartureStatus() {
        Stop__c originStop = [SELECT Id, Route__c FROM Stop__c WHERE Trip__c = 'Destination' LIMIT 1];
        
        Route_Event__c routeEvent = new Route_Event__c(Route__c = originStop.Route__c, Stop__c = originStop.Id,
                                                       Type__c = 'Departure');
        
        Test.startTest();
        insert routeEvent;
        Test.stopTest();
        
        Route__c route = [SELECT Status__c FROM Route__c LIMIT 1];
        
        Assert.areEqual('Delivered', route.Status__c);
    }
}