force-app/main/driver-assistant/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <label>Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Facility__c/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <label>Timezone</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/driver-assistant/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <displayFormat>R-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Route__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Route__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/Stop__c.object-meta.xml
<CustomObject>
    <label>Stop</label>
    <nameField>
        <label>Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Stop__c/fields/Expected_Arrival_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Expected_Arrival_End_Time__c</fullName>
    <label>Expected Arrival End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Expected_Arrival_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Expected_Arrival_Start_Time__c</fullName>
    <label>Expected Arrival Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <label>Sequence Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <label>Trip</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Origin</fullName>
            </value>
            <value>
                <fullName>Stop</fullName>
            </value>
            <value>
                <fullName>Destination</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/driver-assistant/classes/RouteDataService.cls
public without sharing class RouteDataService {

    @InvocableMethod
    public static List<Response> getDeliveryData(List<Request> requests) {
        // Retrieve inputs
        Request input = requests[0];
        Contact inputContact = input.Contact;

//        String inputAccountId = (String) [SELECT Contact.AccountId FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1]?.Contact.AccountId
//                ?? '001aj00000g4CyXAAU';
        //inputAccountId = inputAccountId ?? input.Account.Id;

        // Create expected response
        List<Response> responses = new List<Response>();
        Response output = new Response();
        List<Route__c> routes = [
                SELECT Id, Name, Status__c, (
                        SELECT Id, Expected_Arrival_Start_Time__c, Expected_Arrival_End_Time__c,
                                Trip__c, Sequence_Number__c, Facility__r.Address__c, Facility__r.Phone__c, Facility__r.Timezone__c
                        FROM Stops__r
                        Order By Sequence_Number__c
                )
                FROM Route__c
                WHERE Account__c = :input.Account.Id
        ];

        List<Route> routsWrapper = new List<Route>();
        for (Route__c route : routes) {
            Route routeWrapper = new Route();
            routeWrapper.id = route.Id;
            routeWrapper.name = route.Name;
            routeWrapper.status = route.Status__c;
            List<Stop> stopsWrapper = new List<Stop>();
            routeWrapper.stops = stopsWrapper;
            for (Stop__c stop : route.Stops__r) {
                Stop stopWrapper = new Stop();
                stopWrapper.id = stop.Id;
                stopWrapper.sequenceNumber = stop.Sequence_Number__c;
                stopWrapper.expectedArrivalStartTime = stop.Expected_Arrival_Start_Time__c;
                stopWrapper.expectedArrivalEndTime = stop.Expected_Arrival_End_Time__c;
                stopWrapper.trip = stop.Trip__c;
                stopWrapper.address = String.valueOf(stop.Facility__r.Address__c);
                stopWrapper.timezone = stop.Facility__r.Timezone__c;
                stopWrapper.phone = stop.Facility__r.Phone__c;
                stopsWrapper.add(stopWrapper);
            }
            routsWrapper.add(routeWrapper);
        }

        output.Prompt = JSON.serialize(routsWrapper);
        responses.add(output);

        return responses;
    }

    // Class that represents the template inputs that are passed to the class
    public class Request {
        @InvocableVariable
                // Ensure that the input1 variable is same name with proper case as you configured in the Prompt Builder
        public Contact Contact;
        @InvocableVariable
        public Account Account;
//        @InvocableVariable
//        public String AccountId;
    }

    // Class that represents the data that will be added to the template
    // when it's resolved
    public class Response {
        @InvocableVariable
        public String Prompt;
    }

    public class Route {
        public String id;
        public String name;
        public String status;
        public List<Stop> stops;
    }

    public class Stop {
        public String id;
        public Decimal sequenceNumber;
        public DateTime expectedArrivalStartTime;
        public DateTime expectedArrivalEndTime;
        public String trip;
        public String address;
        public String timezone;
        public String phone;
    }
}