force-app/main/driver-assistant/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <displayFormat>R-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Route__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/driver-assistant/objects/Route_Event__c/Route_Event__c.object-meta.xml
<CustomObject>
    <label>Route Event</label>
    <nameField>
        <label>Route Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Route_Event__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Route Events</relationshipLabel>
    <relationshipName>Route_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Route_Event__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stop</label>
    <referenceTo>Stop__c</referenceTo>
    <relationshipLabel>Route Events</relationshipLabel>
    <relationshipName>Route_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Route_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arrival</fullName>
            </value>
            <value>
                <fullName>Departure</fullName>
            </value>
            <value>
                <fullName>Load</fullName>
            </value>
            <value>
                <fullName>Unload</fullName>
            </value>
            <value>
                <fullName>Delay</fullName>
            </value>
            <value>
                <fullName>Incident</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/Stop__c.object-meta.xml
<CustomObject>
    <label>Stop</label>
    <nameField>
        <label>Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Stop__c/fields/Actual_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Arrival_Time__c</fullName>
    <label>Actual Arrival Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Actual_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Departure_Time__c</fullName>
    <label>Actual Departure Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <label>Trip</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Origin</fullName>
            </value>
            <value>
                <fullName>Stop</fullName>
            </value>
            <value>
                <fullName>Destination</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Origin</fullName>
            </value>
            <value>
                <fullName>Stop</fullName>
            </value>
            <value>
                <fullName>Destination</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/driver-assistant/classes/RouteEventTriggerHandler.cls
public without sharing class RouteEventTriggerHandler {

    private static final List<String> ACTIVE_ROUTE_STATUSES = new List<String>{'New', 'Assigned', 'Accepted'};

    public static void handleAfterInsert(List<Route_Event__c> newRouteEvents) {
        
        Map<Id, String> routesWithStatus = new Map<Id, String>();
        Set<Id> stopIds = new Set<Id>();
        for (Route_Event__c re : newRouteEvents) {
            routesWithStatus.put(re.Route__c, re.Type__c);
            stopIds.add(re.Stop__c);
        }
        
        Map<Id, Stop__c> routesWithStops = new Map<Id, Stop__c>();
        List<Stop__c> stops = [SELECT Id, Route__c, Trip__c FROM Stop__c WHERE Id IN :stopIds];
        for (Stop__c stop : stops) {
            routesWithStops.put(stop.Route__c, stop);            
        }
        List<Route__c> routes = [SELECT Id, Status__c FROM Route__c WHERE Id IN :routesWithStatus.keySet()];
        List<Route__c> routesToUpdate = new List<Route__c>();
        List<Stop__c> stopsToUpdate = new List<Stop__c>();
        for (Route__c route : routes) {
            if (routesWithStatus.get(route.Id) == 'Arrival') {
                if (routesWithStops.get(route.Id) != null) {
                    Stop__c stop = routesWithStops.get(route.Id);
                    stop.Actual_Arrival_Time__c = DateTime.now();
                    stopsToUpdate.add(stop);

                    if (routesWithStops.get(route.Id).Trip__c == 'Origin' && 
                        ACTIVE_ROUTE_STATUSES.contains(route.Status__c)) {
                        route.Status__c = 'In-Progress';
                        routesToUpdate.add(route);
                    }
                }
            } else if (
                routesWithStatus.get(route.Id) == 'Departure' ||
                routesWithStatus.get(route.Id) == 'Unload') 
            {                
                if (routesWithStops.get(route.Id) != null) {
                    Stop__c stop = routesWithStops.get(route.Id);
                    stop.Actual_Departure_Time__c = DateTime.now();
                    stopsToUpdate.add(stop);

                    if (routesWithStops.get(route.Id).Trip__c == 'Destination') {
                        route.Status__c = 'Delivered';
                        routesToUpdate.add(route);
                    }
                }
            }
        }
        
        update routesToUpdate;
        update stopsToUpdate;
    }
    
}