force-app/main/driver-assistant/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <displayFormat>R-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Route__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/driver-assistant/objects/Route_Event__c/Route_Event__c.object-meta.xml
<CustomObject>
    <label>Route Event</label>
    <nameField>
        <label>Route Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Route_Event__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Route Events</relationshipLabel>
    <relationshipName>Route_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Route_Event__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stop</label>
    <referenceTo>Stop__c</referenceTo>
    <relationshipLabel>Route Events</relationshipLabel>
    <relationshipName>Route_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Route_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arrival</fullName>
            </value>
            <value>
                <fullName>Departure</fullName>
            </value>
            <value>
                <fullName>Load</fullName>
            </value>
            <value>
                <fullName>Unload</fullName>
            </value>
            <value>
                <fullName>Delay</fullName>
            </value>
            <value>
                <fullName>Incident</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/Stop__c.object-meta.xml
<CustomObject>
    <label>Stop</label>
    <nameField>
        <label>Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/driver-assistant/objects/Stop__c/fields/Actual_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Arrival_Time__c</fullName>
    <label>Actual Arrival Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Actual_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Departure_Time__c</fullName>
    <label>Actual Departure Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <label>Sequence Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <label>Trip</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Origin</fullName>
            </value>
            <value>
                <fullName>Stop</fullName>
            </value>
            <value>
                <fullName>Destination</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/driver-assistant/objects/Stop__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Origin</fullName>
            </value>
            <value>
                <fullName>Stop</fullName>
            </value>
            <value>
                <fullName>Destination</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/driver-assistant/classes/RouteEventController.cls
public without sharing class RouteEventController {

    private static final List<String> ACTIVE_ROUTE_STATUSES = new List<String>{'New', 'Assigned', 'Accepted'};
    
    @InvocableMethod(label='Create Route Event records' description='Create route event records from prompt response')
    public static List<Response> reportRouteEvent(List<Request> requests) {
        String promptResponse = requests.get(0).promptResponse;
        String routeType = parsePromptResponse(promptResponse, 'Route type -\\s*(\\w+)');
        String sequenceNumber = parsePromptResponse(promptResponse, 'stop number (\\d+)');
        String routeName = parsePromptResponse(promptResponse, '\'([^\']*-[^\']*-*[^\']*)\'');
        String routeEvent = parsePromptResponse(promptResponse, '\'([^\']*)\'');
        Decimal latitude = requests.get(0).latitude;
        Decimal longitude = requests.get(0).longitude;
        Response response = new Response();
        if (sequenceNumber != null && routeName != null && routeEvent != null) {
            response.prompt = createRoutEvent(sequenceNumber, routeName, routeEvent, routeType, promptResponse, latitude, longitude);
        } else if (sequenceNumber == null && routeName != null && routeEvent != null) {
            response.prompt = createRoutEvent(routeName, routeEvent, promptResponse, latitude, longitude);
        } else {
            response.prompt = 'It is not something I can help you with.';
        }
        
        return new List<Response> {response};
    }

    private static String parsePromptResponse(String promptResponse, String regExp) {
        Pattern pattern = Pattern.compile(regExp);
        Matcher matcher = pattern.matcher(promptResponse);

        String matchedString = null;
        if (matcher.find()) {
            matchedString = matcher.group(1);
        }

        return matchedString;
    }

    private static String createRoutEvent(
            String sequenceNumber, String routeName, String event, String routeType,
            String promptResponse, Decimal latitude, Decimal longitude
        ) {
        Integer seqNumber = Integer.valueOf(sequenceNumber);
        Stop__c stop = [SELECT Id, Route__c, Route__r.Status__c, Trip__c
                        FROM Stop__c WHERE Route__r.Name =: routeName 
                        AND Sequence_Number__c =: seqNumber LIMIT 1];
        Route_Event__c routeEvent = new Route_Event__c();
        routeEvent.Name = event;
        routeEvent.Type__c = routeType;
        routeEvent.Route__c = stop.Route__c;
        routeEvent.Stop__c = stop.Id;
        routeEvent.Description__c = event;
        routeEvent.Location__latitude__s = latitude;
        routeEvent.Location__longitude__s  = longitude;
        try {
            insert routeEvent;
        } catch (DmlException dmlEx) {
            return 'It is not something I can help you with.';
        }
        if (routeType == 'Departure')  {
            stop.Actual_Departure_Time__c = DateTime.now();
            update stop;
            if (ACTIVE_ROUTE_STATUSES.contains(stop.Route__r.Status__c)) {
                Route__c route = stop.Route__r;
                route.Status__c = 'In-Progress';
                update route;
            }
        } else if (routeType == 'Arrival' || routeType == 'Unload') {
            stop.Actual_Arrival_Time__c = DateTime.now();
            update stop;
            if (stop.Trip__c == 'Route End') {         
                Route__c route = stop.Route__r;
                route.Status__c = 'Delivered';
                update route;
            }
        }
        return promptResponse;
    }

    private static String createRoutEvent(String routeName, String event, String promptResponse, Decimal latitude, Decimal longitude) {
        Route__c route = [SELECT Id FROM Route__c WHERE Name =: routeName LIMIT 1];
        Route_Event__c routeEvent = new Route_Event__c();
        routeEvent.Name = event;
        routeEvent.Route__c = route.Id;
        routeEvent.Description__c = event;
        routeEvent.Location__latitude__s = latitude;
        routeEvent.Location__longitude__s  = longitude;
        try {
            insert routeEvent;
        } catch (DmlException dmlEx) {
            return 'It is not something I can help you with.';
        }
        return promptResponse;
    }
    
    public class Request {
        @InvocableVariable(label='Prompt Response' required=true)
        public String promptResponse;
        @InvocableVariable(label='Latitude')
        public Decimal latitude;
        @InvocableVariable(label='Longitude ')
        public Decimal longitude;
    }
    
    public class Response {
        @InvocableVariable
        public String prompt;
    }
}